#!/bin/sh

mv /dev/random /dev/random.orig
ln -s /dev/urandom /dev/random

cat > "/hostapd.conf" <<EOF
interface=wlan1
driver=nl80211
hw_mode=g
channel=1
ssid=panther_test
bssid=40:34:56:78:66:66
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
wpa_passphrase=12345678
EOF

cat > "/etc/dnsmasq.conf" <<EOF
dhcp-range=192.168.1.2,192.168.1.254,8h
dhcp-leasefile=/tmp/dnsmasq.leases
pid-file=/tmp/dnsmasq.pid
interface=wlan1
EOF

cat > "/wpa_supplicant.conf" <<EOF
network={
ssid="1x1"
key_mgmt=WPA-PSK
proto=RSN
psk="12345678"
pairwise=CCMP
group=CCMP
}
EOF

iw phy phy0 interface add wlan1 type managed
wpa_supplicant -Dnl80211 -iwlan0 -c /wpa_supplicant.conf &
sleep 2
ifconfig wlan0 192.168.0.199
sleep 2
start-stop-daemon -S -x /usr/sbin/hostapd -- -B -P /var/run/hostapd.pid /hostapd.conf
sleep 2
ifconfig wlan1 192.168.1.1
sleep 2
dnsmasq
