#!/bin/sh

ssid=$1
bssid_last_byte=$2
channel=$4
ht_capab=$5

cat > "/hostapd.conf" <<EOF
interface=wlan0
driver=nl80211
hw_mode=g
channel=${channel:=1}
ssid=${ssid:=panther_test}
bssid=00:34:56:78:66:${bssid_last_byte:=66}
country_code=CN
ieee80211d=1
ieee80211n=1
wmm_enabled=1
wmm_ac_bk_cwmin=4
wmm_ac_bk_cwmax=10
wmm_ac_bk_aifs=7
wmm_ac_bk_txop_limit=0
wmm_ac_bk_acm=0
wmm_ac_be_aifs=3
wmm_ac_be_cwmin=4
wmm_ac_be_cwmax=10
wmm_ac_be_txop_limit=0
wmm_ac_be_acm=0
wmm_ac_vi_aifs=2
wmm_ac_vi_cwmin=3
wmm_ac_vi_cwmax=4
wmm_ac_vi_txop_limit=94
wmm_ac_vi_acm=0
wmm_ac_vo_aifs=2
wmm_ac_vo_cwmin=2
wmm_ac_vo_cwmax=3
wmm_ac_vo_txop_limit=47
wmm_ac_vo_acm=0
EOF
if [ -n "$5" ]; then
cat >> "/hostapd.conf" <<EOF
ht_capab=[HT40$ht_capab]
EOF
fi

if [ -z "$3" -o "$3" != "no_dns" ]; then
cat > "/etc/dnsmasq.conf" <<EOF
dhcp-range=192.168.0.2,192.168.0.254,8h
dhcp-leasefile=/tmp/dnsmasq.leases
pid-file=/tmp/dnsmasq.pid
interface=wlan0
EOF
fi

start-stop-daemon -S -x /usr/sbin/hostapd -- -B -P /var/run/hostapd.pid /hostapd.conf
if [ -z "$3" -o "$3" != "no_dns" ]; then
sleep 2
ifconfig wlan0 192.168.0.1
sleep 2
dnsmasq
fi
