#
#	Copyright (c) 2013, 2017	Montage Inc.	All rights reserved. 
#
obj-$(CONFIG_PANTHER) += generic/

# Ethernet
#obj-$(CONFIG_PANTHER_ETH) += eth/

#WiFi
#obj-$(CONFIG_PANTHER_WLA) += wlan/

#SDHCI
#obj-$(CONFIG_PANTHER_SDHCI) += mmc/

#Sound
#obj-$(CONFIG_PANTHER_SND) += sound/

#obj-$(CONFIG_EARLY_PRINTK)	+=

#EXTRA_CFLAGS += -Werror
#
# 	Uncomment to use Switch Port0 as WAN port
#
#EXTRA_CFLAGS += -DCML_WAN_P0
