#!/bin/sh

# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

mount_no_mtd() {
	mkdir -p /tmp/etc
	mount -t mini_fo -o base=/etc,sto=/tmp/etc "mini_fo:/tmp/etc" /etc 2>&-
}

check_for_mtd() {
    check_skip || {
	grep -qs rootfs_data /proc/mtd || {
	    mount_no_mtd && pi_mount_skip_next=true
	}
    }
}

boot_hook_add preinit_mount_root check_for_mtd

